### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by gentookid** [cutelyst/simple-mail#107]
Hello everyone, I'm trying to use the module inside some testbed code, so I've gone ahead and included the folder into the project, and followed the demos to setup the mail test sending, however, upon buidling, I'm greeted with a lot of warnings regarding incoherent dll linking, and some more about MOC code being generated that is not correct.
I'm trying this with Qt-5.14.1, using MSVC compiler,maybe this is due to incorrect inclusion of the files?

**Comment by dantti** [comment]
pretty much incorrect inclusion, add_subdirectory() and adding the linking targets to your project is the only thing you need to do

**Comment by gentookid** [comment]
Thanks for the prompt answer, I think maybe the problem can also be related to me not using cmake currently, but the previous system.

How would I go about adding it to my current project file (QMake based)?

**Comment by dantti** [comment]
Then that's not supported, can be done, but highly recommend stop using qmake :)

**Comment by gentookid** [comment]
Welp, I think it might be time to, the proyect ain't really big, it does link to openssl as the only external tool for CMS, guess I'll go straight to the migration guide, thanks!

**Comment by gentookid** [comment]
dantii, thanks for the pointers, so far I've created a testbed proyect using Qt 6.8.0, qt creator 14.0.2, and both mingw and msvc (currently targeting release on mingw)

However, using the code from demo1, I get a crash when running after message.addPart() (server->sendMail never gets called) -added some qDebug() calls to check where it was happening, not the best practice I know)

To my CMakeList project I've added 
<code>
add_subdirectory(Dependencias/simple-mail-3.0.0/)
target_link_libraries(MigraPrueba PRIVATE SimpleMail::Core)
</code>
Dependencias folder is on the same folder that main.cpp and the code files are.

And at the very bottom of the file(since QtCreator was complaining that this was missing and might cause it to fail):
<code>
target_link_libraries(MigraPrueba PRIVATE Qt6::Network)
</code>

Am I still missing something? The rest of the code was copy+pasted from demo1, switching the password and email address for login, and the include directive at the very top looks like;

<code>
#include "Dependencias/simple-mail-3.0.0/src/SimpleMail"
</code>

**Comment by 640kb** [comment]
> Am I still missing something? The rest of the code was copy+pasted from demo1, switching the password and email address for login, and the include directive at the very top looks like;
> ` #include "Dependencias/simple-mail-3.0.0/src/SimpleMail" `
> 
> EDIT: Crash occurs when accesing *d->content; on line 195 from mimemessage.cpp
> 
> EDIT2: After reading and trying to understand the underlying code,I changed: ` auto content = *d->content; ` to: ` auto content = d->content; `
> 
> Now the code builds and runs, but is this proposed solution good enough?

If I see it correctly, you are not using the latest version of the master branch, but the tagged version 3.0.0? The error should be corrected in the master branch.

**Comment by gentookid** [comment]
That's correct, fixing that made it go through, however would you recommend using the master branch directly?

**Comment by 640kb** [comment]
I would say it depends if you want to use the library in a production environment, then a stable branch would be recommended. Otherwise, it helps the project more if many people test the master branch.

**Comment by dantti** [comment]
closing as v3.1.0 is out
