### ISSUE TITLE
How to install this to windows Visual Studio QT project?

### ISSUE THREAD

**Issue by bfilipiuk** [cutelyst/simple-mail#108]
Hello everyone, 
I'm creating Qt project in Visual Studio and I struggle with implementing this library to my project. I've tried different ways to compile and link it but every way I try is leading to tons of errors and some features seems unavailable in VS (?). I feel like I'm missing something obvious.

Please note that I'm a beginner at installing custom C++ libs and I might need bit more specific (maybe step-by-step) walkthrough about installing this in a correct way.

**Comment by dantti** [comment]
This is a CMake project, you should learn it first.

**Comment by bfilipiuk** [comment]
Thanks for your fast reply. I've tried to follow different tutorials of cmake without success. Are you able to provide me one that will lead to successful implementation? I'm pretty sure it's few minutes for you and sadly I'm tight with time. You would help me and others a lot.
