### ISSUE TITLE
simple-mail-master\build\src\simplemail-qt5_autogen\include_Debug\EWIEGA46WW/moc_sender.cpp(197): error C2491: 'SimpleMail::Sender::staticMetaObject': definition of dllimport static data member not allowed

### ISSUE THREAD

**Issue by opengpu** [cutelyst/simple-mail#14]
simple-mail-master\build\src\simplemail-qt5_autogen\include_Debug\EWIEGA46WW/moc_sender.cpp(197): error C2491: 'SimpleMail::Sender::staticMetaObject': definition of dllimport static data member not allowed

**Comment by opengpu** [comment]
vs2017, x64, 
Qt\5.12.3\msvc2017_64\lib\cmake\Qt5\Qt5Config.cmake

**Comment by dantti** [comment]
Sorry I don't use Windows, so I have no idea of what this error is about, does it happen if you use VCPKG or another compiler? if you find out I can accept a Pull Request.

**Comment by opengpu** [comment]
when cmake, i just choose visual studio 15 2017, x64, use default native compilers

**Comment by opengpu** [comment]
i add SMTP_BUILD in Preprocessors Definations, then the dll can compile successfully.

**Comment by dantti** [comment]
odd, what SMTP_BUILD contains? Tho I should do a modernization to this library CMake files...

**Comment by opengpu** [comment]
#ifndef SMTPEXPORTS_H
#define SMTPEXPORTS_H

#ifdef SMTP_BUILD
#define SMTP_EXPORT Q_DECL_EXPORT
#else
#define SMTP_EXPORT Q_DECL_IMPORT
#endif

#endif // SMTPEXPORTS_H

**Comment by dantti** [comment]
It's properly fixed now
