### ISSUE TITLE
Undefined references

### ISSUE THREAD

**Issue by tichun** [cutelyst/simple-mail#16]
Under Windows I get over a hundred of undefined references in MOC files when builiding the project. This doesn't happen under Ubuntu.
Can you reproduce it or is it my setup? I'm compiling with MinGW (172 errors) or Clang (114 errors) as MSVC won't work with this project at all.
![image](https://user-images.githubusercontent.com/35684943/57980182-de18ef00-7a27-11e9-8530-a7a1af443330.png)

**Comment by dantti** [comment]
I don't have Windows, but might be related to #14

**Comment by tichun** [comment]
add_compile_definitions(SMTP_BUILD) solved the problem.
Sorry for bothering.

**Comment by inejose** [comment]
hi @tichun , where did you include it? in which file exactly? thanks! :)
