### ISSUE TITLE
Bug in mimepart - missing trailing equal characters

### ISSUE THREAD

**Issue by ludekvodicka** [cutelyst/simple-mail#20]
I'm using your library to communicate with amazon SES which requires ending == for base64 encoded content

https://github.com/cutelyst/simple-mail/compare/master...ludekvodicka:patch-2

(I'm not sure if the current state was bug or intention because of another email service).

**Comment by dantti** [comment]
Hi, sorry for the delay, I'm not sure why it is omitting the trailing equals, but if it helps you have this working please do a PR, just add a note above that line so if in future someone complains about the opposite we can add a configuration option.
Thanks

**Comment by ludekvodicka** [comment]
Sure. Added

**Comment by dantti** [comment]
merged thanks
