### ISSUE TITLE
SMTP response code too strict

### ISSUE THREAD

**Issue by DerDakon** [cutelyst/simple-mail#28]
The server will indeed return 250 to most commands, but e.g. 251 is permitted at some places. Basically one should see any 2xx code as success for most normal commands (i.e. after the EHLO).

**Comment by dantti** [comment]
Perhaps a list of accepted codes? I read in RFC that for RCTP commands 250 251 and 252 are success ones.

**Comment by Loclay** [comment]
/home/user/simple-mail/demos/async1/async1.cpp:22:105: error: incorrect conversion from «const char*» в «int» [-fpermissive]
     message.setSender(SimpleMail::EmailAddress(QLatin1String("your_email_address@gmail.com", "Your Name")));

**Comment by dantti** [comment]
@Loclay your issue is a misuse of QLatin1String (check where you're closing parenthesis) and is not related in anyway with this issue.

**Comment by dantti** [comment]
closing due no reply
