### ISSUE TITLE
Adding to Qt project throws "unresolved external symbol" errors

### ISSUE THREAD

**Issue by Sv443** [cutelyst/simple-mail#30]
I am currently trying to add this library to my Qt project but I have never done this before.  
I've looked through the Qt documentation on adding external libraries and have found and tried some ways to add the library, but they all failed.  
  
I've tried:
- adding the path to the `src` folder to my project's `.pro` file like this: `INCLUDEPATH += "../Simple-Mail/src"`
- creating a `.pri` file in the `Simple-Mail` folder, adding `INCLUDEPATH += ./src` to it and using `!include( ../Simple-Mail/SimpleMail.pri ) {}` to include it in my main `.pro` file
- using a raw path to access the headers (`#include "../Simple-Mail/src/SmtpMime"`)
  
Every time the syntax highlighting, code suggestions and linter didn't give me any errors but upon building my project I get about 20 "unresolved external symbol" errors.  
What am I doing wrong?

**Comment by dakejahl** [comment]
Same here

**Comment by dantti** [comment]
You should tell qmake to find it via pkgconfig or use CMake on your project.

**Comment by dakejahl** [comment]
Could you provide an example of how to do this? Right now I am trying to add it via a `.pri` file but having no luck. I was able to get https://github.com/bluetiger9/SmtpClient-for-Qt working but was having issues with failing the login authentication (reponse code 535) 😕 so here I am seeing if this will work instead.

**Comment by Sv443** [comment]
> 
> 
> You should tell qmake to find it via pkgconfig or use CMake on your project.

I couldn't find any information on how to do this that worked. Like @dakejahl said, maybe you could provide an example?

**Comment by dantti** [comment]
https://doc.qt.io/qt-5/qmake-project-files.html#configuration-features

**Comment by dantti** [comment]
`PKGCONFIG += simplemail2-qt5`
