### ISSUE TITLE
Building with MSVC?

### ISSUE THREAD

**Issue by gentookid** [cutelyst/simple-mail#33]
Hey all, I stumled across your proyect, and upon trying to build it, I get warnings from msvc about dll linking being incoherent (sorry, badly translated from spanish)

Does the project have any specific requirements?

**Comment by dantti** [comment]
should build fine, just need a C++11 compiler

**Comment by gentookid** [comment]
Maybe I'm dping something wrong, using MSVC && cmake, opening the Qt Command Prompt with Qt 5.14.1, I'm not able to build.
Sitting on root of master branch, doing cmake src makes no errors, but has some warnings (that can be disabled with -Wno-dev)

Upon calling cmake demos/demo1, it does not create a makefile for me to call upon nmake..

I also tryied to just add the source to a test proyect in Qt Creator, and it does give some errors regarding "incoherent linking".

cl version is 19.00.24245, cmake 3.16, qt 5.14.1

Maybe I'm the one doing it wrong, sorry to ask for this but could you clarify?

Regards

**Comment by dantti** [comment]
well I can't see what's wrong, maybe paste some errors/warnings?
I also don't use Windows/MSVC but I know there are Windows users.

**Comment by gentookid** [comment]
Sure, what I get is the following upon building:
`
	C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.Debug
	cl -c -nologo -Zc:wchar_t -FS -Zc:rvalueCast -Zc:inline -Zc:strictStrings -Zc:throwingNew -Zc:referenceBinding -Zc:__cplusplus -Zi -MDd -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc /Fddebug\Mailer.vc.pdb -DUNICODE -D_UNICODE -DWIN32 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I..\Mailer -I. -I..\..\..\Qt\5.14.1\msvc2017\include -I..\..\..\Qt\5.14.1\msvc2017\include\QtGui -I..\..\..\Qt\5.14.1\msvc2017\include\QtANGLE -I..\..\..\Qt\5.14.1\msvc2017\include\QtNetwork -I..\..\..\Qt\5.14.1\msvc2017\include\QtCore -Idebug -I/include -I..\..\..\Qt\5.14.1\msvc2017\mkspecs\win32-msvc -Fodebug\ @C:\Users\raz0r\AppData\Local\Temp\sender.obj.9092.32.jom
sender.cpp
	cl -c -nologo -Zc:wchar_t -FS -Zc:rvalueCast -Zc:inline -Zc:strictStrings -Zc:throwingNew -Zc:referenceBinding -Zc:__cplusplus -Zi -MDd -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc /Fddebug\Mailer.vc.pdb -DUNICODE -D_UNICODE -DWIN32 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I..\Mailer -I. -I..\..\..\Qt\5.14.1\msvc2017\include -I..\..\..\Qt\5.14.1\msvc2017\include\QtGui -I..\..\..\Qt\5.14.1\msvc2017\include\QtANGLE -I..\..\..\Qt\5.14.1\msvc2017\include\QtNetwork -I..\..\..\Qt\5.14.1\msvc2017\include\QtCore -Idebug -I/include -I..\..\..\Qt\5.14.1\msvc2017\mkspecs\win32-msvc -Fodebug\ @C:\Users\raz0r\AppData\Local\Temp\serverreply.obj.9092.47.jom
serverreply.cpp
..\Mailer\src\serverreply.cpp(21): warning C4273: 'SimpleMail::ServerReply::ServerReply': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\serverreply.h(31): note: vea la definici¢n anterior de '{ctor}'
..\Mailer\src\serverreply.cpp(28): warning C4273: 'SimpleMail::ServerReply::~ServerReply': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\serverreply.h(32): note: vea la definici¢n anterior de '{dtor}'
..\Mailer\src\serverreply.cpp(33): warning C4273: 'SimpleMail::ServerReply::error': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\serverreply.h(34): note: vea la definici¢n anterior de 'error'
..\Mailer\src\serverreply.cpp(39): warning C4273: 'SimpleMail::ServerReply::responseCode': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\serverreply.h(36): note: vea la definici¢n anterior de 'responseCode'
..\Mailer\src\serverreply.cpp(45): warning C4273: 'SimpleMail::ServerReply::responseText': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\serverreply.h(37): note: vea la definici¢n anterior de 'responseText'
..\Mailer\src\serverreply.cpp(51): warning C4273: 'SimpleMail::ServerReply::finish': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\serverreply.h(43): note: vea la definici¢n anterior de 'finish'
C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\debug\moc_serverreply.cpp(67): warning C4273: 'SimpleMail::ServerReply::qt_static_metacall': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\serverreply.h(28): note: vea la definici¢n anterior de 'qt_static_metacall'
C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\debug\moc_serverreply.cpp(88): warning C4273: 'staticMetaObject': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\serverreply.h(28): note: vea la definici¢n anterior de 'public: static QMetaObject const SimpleMail::ServerReply::staticMetaObject'
C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\debug\moc_serverreply.cpp(88): error C2491: 'SimpleMail::ServerReply::staticMetaObject': definici¢n de miembro de datos est tico dllimport no permitida
C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\debug\moc_serverreply.cpp(99): warning C4273: 'SimpleMail::ServerReply::metaObject': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\serverreply.h(28): note: vea la definici¢n anterior de 'metaObject'
C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\debug\moc_serverreply.cpp(104): warning C4273: 'SimpleMail::ServerReply::qt_metacast': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\serverreply.h(28): note: vea la definici¢n anterior de 'qt_metacast'
C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\debug\moc_serverreply.cpp(112): warning C4273: 'SimpleMail::ServerReply::qt_metacall': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\serverreply.h(28): note: vea la definici¢n anterior de 'qt_metacall'
C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\debug\moc_serverreply.cpp(130): warning C4273: 'SimpleMail::ServerReply::finished': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\serverreply.h(40): note: vea la definici¢n anterior de 'finished'
..\Mailer\src\sender.cpp(29): warning C4273: 'SimpleMail::Sender::Sender': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(70): note: vea la definici¢n anterior de '{ctor}'
..\Mailer\src\sender.cpp(35): warning C4273: 'SimpleMail::Sender::Sender': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(71): note: vea la definici¢n anterior de '{ctor}'
..\Mailer\src\sender.cpp(47): warning C4273: 'SimpleMail::Sender::~Sender': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(72): note: vea la definici¢n anterior de '{dtor}'
..\Mailer\src\sender.cpp(52): warning C4273: 'SimpleMail::Sender::host': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(77): note: vea la definici¢n anterior de 'host'
..\Mailer\src\sender.cpp(58): warning C4273: 'SimpleMail::Sender::setUser': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(124): note: vea la definici¢n anterior de 'setUser'
..\Mailer\src\sender.cpp(67): warning C4273: 'SimpleMail::Sender::password': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(129): note: vea la definici¢n anterior de 'password'
..\Mailer\src\sender.cpp(73): warning C4273: 'SimpleMail::Sender::setPassword': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(134): note: vea la definici¢n anterior de 'setPassword'
..\Mailer\src\sender.cpp(82): warning C4273: 'SimpleMail::Sender::authMethod': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(139): note: vea la definici¢n anterior de 'authMethod'
..\Mailer\src\sender.cpp(88): warning C4273: 'SimpleMail::Sender::setAuthMethod': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(144): note: vea la definici¢n anterior de 'setAuthMethod'
..\Mailer\src\sender.cpp(94): warning C4273: 'SimpleMail::Sender::setHost': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(82): note: vea la definici¢n anterior de 'setHost'
..\Mailer\src\sender.cpp(100): warning C4273: 'SimpleMail::Sender::port': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(87): note: vea la definici¢n anterior de 'port'
..\Mailer\src\sender.cpp(106): warning C4273: 'SimpleMail::Sender::setPort': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(92): note: vea la definici¢n anterior de 'setPort'
..\Mailer\src\sender.cpp(112): warning C4273: 'SimpleMail::Sender::name': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(98): note: vea la definici¢n anterior de 'name'
..\Mailer\src\sender.cpp(118): warning C4273: 'SimpleMail::Sender::setName': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(104): note: vea la definici¢n anterior de 'setName'
..\Mailer\src\sender.cpp(124): warning C4273: 'SimpleMail::Sender::connectionType': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(109): note: vea la definici¢n anterior de 'connectionType'
..\Mailer\src\sender.cpp(130): warning C4273: 'SimpleMail::Sender::setConnectionType': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(114): note: vea la definici¢n anterior de 'setConnectionType'
..\Mailer\src\sender.cpp(154): warning C4273: 'SimpleMail::Sender::user': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(119): note: vea la definici¢n anterior de 'user'
..\Mailer\src\sender.cpp(160): warning C4273: 'SimpleMail::Sender::responseText': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(149): note: vea la definici¢n anterior de 'responseText'
..\Mailer\src\sender.cpp(166): warning C4273: 'SimpleMail::Sender::responseCode': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(154): note: vea la definici¢n anterior de 'responseCode'
..\Mailer\src\sender.cpp(172): warning C4273: 'SimpleMail::Sender::connectionTimeout': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(159): note: vea la definici¢n anterior de 'connectionTimeout'
..\Mailer\src\sender.cpp(178): warning C4273: 'SimpleMail::Sender::setConnectionTimeout': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(164): note: vea la definici¢n anterior de 'setConnectionTimeout'
..\Mailer\src\sender.cpp(184): warning C4273: 'SimpleMail::Sender::responseTimeout': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(169): note: vea la definici¢n anterior de 'responseTimeout'
..\Mailer\src\sender.cpp(190): warning C4273: 'SimpleMail::Sender::setResponseTimeout': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(174): note: vea la definici¢n anterior de 'setResponseTimeout'
..\Mailer\src\sender.cpp(195): warning C4273: 'SimpleMail::Sender::sendMessageTimeout': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(179): note: vea la definici¢n anterior de 'sendMessageTimeout'
..\Mailer\src\sender.cpp(200): warning C4273: 'SimpleMail::Sender::setSendMessageTimeout': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(184): note: vea la definici¢n anterior de 'setSendMessageTimeout'
..\Mailer\src\sender.cpp(206): warning C4273: 'SimpleMail::Sender::ignoreSslErrors': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(190): note: vea la definici¢n anterior de 'ignoreSslErrors'
..\Mailer\src\sender.cpp(215): warning C4273: 'SimpleMail::Sender::ignoreSslErrors': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(197): note: vea la definici¢n anterior de 'ignoreSslErrors'
..\Mailer\src\sender.cpp(224): warning C4273: 'SimpleMail::Sender::setPeerVerificationType': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(203): note: vea la definici¢n anterior de 'setPeerVerificationType'
..\Mailer\src\sender.cpp(230): warning C4273: 'SimpleMail::Sender::peerVerificationType': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(209): note: vea la definici¢n anterior de 'peerVerificationType'
..\Mailer\src\sender.cpp(236): warning C4273: 'SimpleMail::Sender::sendMail': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(211): note: vea la definici¢n anterior de 'sendMail'
..\Mailer\src\sender.cpp(242): warning C4273: 'SimpleMail::Sender::lastError': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(213): note: vea la definici¢n anterior de 'lastError'
..\Mailer\src\sender.cpp(248): warning C4273: 'SimpleMail::Sender::quit': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(215): note: vea la definici¢n anterior de 'quit'
..\Mailer\src\sender.cpp(254): warning C4273: 'SimpleMail::Sender::socketStateChanged': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(218): note: vea la definici¢n anterior de 'socketStateChanged'
..\Mailer\src\sender.cpp(258): warning C4273: 'SimpleMail::Sender::socketError': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(219): note: vea la definici¢n anterior de 'socketError'
..\Mailer\src\sender.cpp(262): warning C4273: 'SimpleMail::Sender::socketReadyRead': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(220): note: vea la definici¢n anterior de 'socketReadyRead'
C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\debug\moc_sender.cpp(144): warning C4273: 'SimpleMail::Sender::qt_static_metacall': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(32): note: vea la definici¢n anterior de 'qt_static_metacall'
C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\debug\moc_sender.cpp(200): warning C4273: 'staticMetaObject': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(32): note: vea la definici¢n anterior de 'public: static QMetaObject const SimpleMail::Sender::staticMetaObject'
C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\debug\moc_sender.cpp(200): error C2491: 'SimpleMail::Sender::staticMetaObject': definici¢n de miembro de datos est tico dllimport no permitida
C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\debug\moc_sender.cpp(211): warning C4273: 'SimpleMail::Sender::metaObject': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(32): note: vea la definici¢n anterior de 'metaObject'
C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\debug\moc_sender.cpp(216): warning C4273: 'SimpleMail::Sender::qt_metacast': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(32): note: vea la definici¢n anterior de 'qt_metacast'
C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\debug\moc_sender.cpp(224): warning C4273: 'SimpleMail::Sender::qt_metacall': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(32): note: vea la definici¢n anterior de 'qt_metacall'
C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\debug\moc_sender.cpp(242): warning C4273: 'SimpleMail::Sender::smtpError': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(223): note: vea la definici¢n anterior de 'smtpError'
C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\debug\moc_sender.cpp(249): warning C4273: 'SimpleMail::Sender::sslErrors': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\sender.h(224): note: vea la definici¢n anterior de 'sslErrors'
	cl -c -nologo -Zc:wchar_t -FS -Zc:rvalueCast -Zc:inline -Zc:strictStrings -Zc:throwingNew -Zc:referenceBinding -Zc:__cplusplus -Zi -MDd -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc /Fddebug\Mailer.vc.pdb -DUNICODE -D_UNICODE -DWIN32 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I..\Mailer -I. -I..\..\..\Qt\5.14.1\msvc2017\include -I..\..\..\Qt\5.14.1\msvc2017\include\QtGui -I..\..\..\Qt\5.14.1\msvc2017\include\QtANGLE -I..\..\..\Qt\5.14.1\msvc2017\include\QtNetwork -I..\..\..\Qt\5.14.1\msvc2017\include\QtCore -Idebug -I/include -I..\..\..\Qt\5.14.1\msvc2017\mkspecs\win32-msvc -Fodebug\ @C:\Users\raz0r\AppData\Local\Temp\server.obj.9092.47.jom
server.cpp
..\Mailer\src\server.cpp(30): warning C4273: 'SimpleMail::Server::Server': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(69): note: vea la definici¢n anterior de '{ctor}'
..\Mailer\src\server.cpp(38): warning C4273: 'SimpleMail::Server::~Server': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(70): note: vea la definici¢n anterior de '{dtor}'
..\Mailer\src\server.cpp(43): warning C4273: 'SimpleMail::Server::host': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(75): note: vea la definici¢n anterior de 'host'
..\Mailer\src\server.cpp(49): warning C4273: 'SimpleMail::Server::setHost': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(80): note: vea la definici¢n anterior de 'setHost'
..\Mailer\src\server.cpp(55): warning C4273: 'SimpleMail::Server::port': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(85): note: vea la definici¢n anterior de 'port'
..\Mailer\src\server.cpp(61): warning C4273: 'SimpleMail::Server::setPort': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(90): note: vea la definici¢n anterior de 'setPort'
..\Mailer\src\server.cpp(67): warning C4273: 'SimpleMail::Server::hostname': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(95): note: vea la definici¢n anterior de 'hostname'
..\Mailer\src\server.cpp(73): warning C4273: 'SimpleMail::Server::setHostname': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(101): note: vea la definici¢n anterior de 'setHostname'
..\Mailer\src\server.cpp(79): warning C4273: 'SimpleMail::Server::connectionType': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(106): note: vea la definici¢n anterior de 'connectionType'
..\Mailer\src\server.cpp(85): warning C4273: 'SimpleMail::Server::setConnectionType': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(111): note: vea la definici¢n anterior de 'setConnectionType'
..\Mailer\src\server.cpp(93): warning C4273: 'SimpleMail::Server::username': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(116): note: vea la definici¢n anterior de 'username'
..\Mailer\src\server.cpp(99): warning C4273: 'SimpleMail::Server::setUsername': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(121): note: vea la definici¢n anterior de 'setUsername'
..\Mailer\src\server.cpp(108): warning C4273: 'SimpleMail::Server::password': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(126): note: vea la definici¢n anterior de 'password'
..\Mailer\src\server.cpp(114): warning C4273: 'SimpleMail::Server::setPassword': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(131): note: vea la definici¢n anterior de 'setPassword'
..\Mailer\src\server.cpp(120): warning C4273: 'SimpleMail::Server::authMethod': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(136): note: vea la definici¢n anterior de 'authMethod'
..\Mailer\src\server.cpp(126): warning C4273: 'SimpleMail::Server::setAuthMethod': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(141): note: vea la definici¢n anterior de 'setAuthMethod'
..\Mailer\src\server.cpp(132): warning C4273: 'SimpleMail::Server::sendMail': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(154): note: vea la definici¢n anterior de 'sendMail'
..\Mailer\src\server.cpp(150): warning C4273: 'SimpleMail::Server::queueSize': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(161): note: vea la definici¢n anterior de 'queueSize'
..\Mailer\src\server.cpp(156): warning C4273: 'SimpleMail::Server::connectToServer': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(168): note: vea la definici¢n anterior de 'connectToServer'
..\Mailer\src\server.cpp(184): warning C4273: 'SimpleMail::Server::ignoreSslErrors': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(174): note: vea la definici¢n anterior de 'ignoreSslErrors'
..\Mailer\src\server.cpp(193): warning C4273: 'SimpleMail::Server::ignoreSslErrors': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(180): note: vea la definici¢n anterior de 'ignoreSslErrors'
C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\debug\moc_server.cpp(126): warning C4273: 'SimpleMail::Server::qt_static_metacall': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(31): note: vea la definici¢n anterior de 'qt_static_metacall'
C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\debug\moc_server.cpp(154): warning C4273: 'staticMetaObject': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(31): note: vea la definici¢n anterior de 'public: static QMetaObject const SimpleMail::Server::staticMetaObject'
C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\debug\moc_server.cpp(154): error C2491: 'SimpleMail::Server::staticMetaObject': definici¢n de miembro de datos est tico dllimport no permitida
C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\debug\moc_server.cpp(165): warning C4273: 'SimpleMail::Server::metaObject': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(31): note: vea la definici¢n anterior de 'metaObject'
C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\debug\moc_server.cpp(170): warning C4273: 'SimpleMail::Server::qt_metacast': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(31): note: vea la definici¢n anterior de 'qt_metacast'
C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\debug\moc_server.cpp(178): warning C4273: 'SimpleMail::Server::qt_metacall': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(31): note: vea la definici¢n anterior de 'qt_metacall'
C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\debug\moc_server.cpp(196): warning C4273: 'SimpleMail::Server::smtpError': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(183): note: vea la definici¢n anterior de 'smtpError'
C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\debug\moc_server.cpp(203): warning C4273: 'SimpleMail::Server::sslErrors': vinculaci¢n de DLL incoherente
C:\Desarrollo\Desarrollo\Mailer\src\server.h(184): note: vea la definici¢n anterior de 'sslErrors'
jom: C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\Makefile.Debug [debug\sender.obj] Error 2
jom: C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\Makefile.Debug [debug\server.obj] Error 2
jom: C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\Makefile.Debug [debug\serverreply.obj] Error 2
jom: C:\Desarrollo\Desarrollo\build-Mailer-Desktop_Qt_5_14_1_MSVC2017_32bit-Debug\Makefile [debug] Error 2
`

The Kit is being used actively on other projects, I don't know if I'm missing anything though..
The source for main is:
`
#include <QCoreApplication>
#include "src/server.h"
#include "src/mimemessage.h"
#include "src/mimetext.h"
#include "src/serverreply.h"
#include "src/sender.h"
#include <QDebug>
int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);
    SimpleMail::Sender sender("smtp.gmail.com", 465, SimpleMail::Sender::SslConnection);

    // We need to set the username (your email address) and the password
    // for smtp authentification.
    sender.setUser("linuxkid.zeuz@gmail.com");
    sender.setPassword("*321456987*abcd");

    // Now we create a MimeMessage object. This will be the email.
    SimpleMail::MimeMessage message;
    message.setSender(SimpleMail::EmailAddress("linuxkid.zeuz@gmail.com", "Anibal Francisco Martinez Cortina"));
    message.addTo(SimpleMail::EmailAddress("Anibal Francisco Martinez Cortina<linuxkid.zeuz@gmail.com>"));
    message.setSubject("Testing Subject");

    // First we create a MimeText object.
    SimpleMail::MimeText text;

    // Now add some text to the email.
    text.setText("Hi,\nThis is a simple email message.\n");

    // Now add it to the mail
    message.addPart(&text);

    // Now we can send the mail
    sender.sendMail(message); // Blocks untill mail is delivered or errored
    return a.exec();
}
`

And the project file is just:
`
QT += gui core network

CONFIG += c++11 console
CONFIG -= app_bundle

# The following define makes your compiler emit warnings if you use
# any Qt feature that has been marked deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
        main.cpp \
        src/emailaddress.cpp \
        src/mimeattachment.cpp \
        src/mimecontentformatter.cpp \
        src/mimefile.cpp \
        src/mimehtml.cpp \
        src/mimeinlinefile.cpp \
        src/mimemessage.cpp \
        src/mimemultipart.cpp \
        src/mimepart.cpp \
        src/mimetext.cpp \
        src/quotedprintable.cpp \
        src/sender.cpp \
        src/server.cpp \
        src/serverreply.cpp

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

HEADERS += \
    src/emailaddress.h \
    src/emailaddress_p.h \
    src/mimeattachment.h \
    src/mimecontentformatter.h \
    src/mimefile.h \
    src/mimehtml.h \
    src/mimeinlinefile.h \
    src/mimemessage.h \
    src/mimemessage_p.h \
    src/mimemultipart.h \
    src/mimemultipart_p.h \
    src/mimepart.h \
    src/mimepart_p.h \
    src/mimetext.h \
    src/quotedprintable.h \
    src/sender.h \
    src/sender_p.h \
    src/server.h \
    src/server_p.h \
    src/serverreply.h \
    src/serverreply_p.h \
    src/smtpexports.h
`

**Comment by dantti** [comment]
Well from your qmake you are importing all simple-mail sources, you need to compile it first, creating a .dll then link to that dll and include it's headers. Doing this on Windows is usually a pitta and I'm not very familiar with best places to install stuff, perhaps in future I create a VCPKG for it, I'd also advise agains't using qmake as it's going to be deprecated from Qt.

**Comment by gentookid** [comment]
Hey, didn't know about qmake being deprecated actually.. What's its preplacement going to be?

Also, after reading a little of the source I just removed the include for smtpexport and removed the SMTP_EXPORT class, and built it bundled.. And it worked, dunno if this is against the rules, so please do let me know

**Comment by dantti** [comment]
CMake is likely to be the default build system for Qt6, if you bundle it your code must be (L)GPL if you distribute your application.
