### ISSUE TITLE
Build Failed With MSCV

### ISSUE THREAD

**Issue by steveobbayi** [cutelyst/simple-mail#34]
I'm getting issues building this with MSCV. The previous version (simple-mail-1.4.0) did build without any issues. I am using VS2019, issue is still there with VS2017. I noticed another user had a similar issue and it was closed, not sure why. Here are the error messages.

1>------ Build started: Project: ZERO_CHECK, Configuration: Release x64 ------
1>Checking Build System
2>------ Build started: Project: SimpleMail2Qt5, Configuration: Release x64 ------
2>Automatic MOC for target SimpleMail2Qt5
2>sender.cpp
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(29): warning C4273: 'SimpleMail::Sender::Sender': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(70): note: see previous definition of '{ctor}'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(35): warning C4273: 'SimpleMail::Sender::Sender': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(71): note: see previous definition of '{ctor}'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(47): warning C4273: 'SimpleMail::Sender::~Sender': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(72): note: see previous definition of '{dtor}'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(52): warning C4273: 'SimpleMail::Sender::host': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(77): note: see previous definition of 'host'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(58): warning C4273: 'SimpleMail::Sender::setUser': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(124): note: see previous definition of 'setUser'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(67): warning C4273: 'SimpleMail::Sender::password': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(129): note: see previous definition of 'password'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(73): warning C4273: 'SimpleMail::Sender::setPassword': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(134): note: see previous definition of 'setPassword'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(82): warning C4273: 'SimpleMail::Sender::authMethod': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(139): note: see previous definition of 'authMethod'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(88): warning C4273: 'SimpleMail::Sender::setAuthMethod': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(144): note: see previous definition of 'setAuthMethod'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(94): warning C4273: 'SimpleMail::Sender::setHost': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(82): note: see previous definition of 'setHost'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(100): warning C4273: 'SimpleMail::Sender::port': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(87): note: see previous definition of 'port'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(106): warning C4273: 'SimpleMail::Sender::setPort': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(92): note: see previous definition of 'setPort'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(112): warning C4273: 'SimpleMail::Sender::name': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(98): note: see previous definition of 'name'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(118): warning C4273: 'SimpleMail::Sender::setName': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(104): note: see previous definition of 'setName'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(124): warning C4273: 'SimpleMail::Sender::connectionType': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(109): note: see previous definition of 'connectionType'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(130): warning C4273: 'SimpleMail::Sender::setConnectionType': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(114): note: see previous definition of 'setConnectionType'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(154): warning C4273: 'SimpleMail::Sender::user': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(119): note: see previous definition of 'user'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(160): warning C4273: 'SimpleMail::Sender::responseText': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(149): note: see previous definition of 'responseText'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(166): warning C4273: 'SimpleMail::Sender::responseCode': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(154): note: see previous definition of 'responseCode'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(172): warning C4273: 'SimpleMail::Sender::connectionTimeout': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(159): note: see previous definition of 'connectionTimeout'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(178): warning C4273: 'SimpleMail::Sender::setConnectionTimeout': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(164): note: see previous definition of 'setConnectionTimeout'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(184): warning C4273: 'SimpleMail::Sender::responseTimeout': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(169): note: see previous definition of 'responseTimeout'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(190): warning C4273: 'SimpleMail::Sender::setResponseTimeout': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(174): note: see previous definition of 'setResponseTimeout'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(195): warning C4273: 'SimpleMail::Sender::sendMessageTimeout': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(179): note: see previous definition of 'sendMessageTimeout'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(200): warning C4273: 'SimpleMail::Sender::setSendMessageTimeout': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(184): note: see previous definition of 'setSendMessageTimeout'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(206): warning C4273: 'SimpleMail::Sender::ignoreSslErrors': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(190): note: see previous definition of 'ignoreSslErrors'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(215): warning C4273: 'SimpleMail::Sender::ignoreSslErrors': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(197): note: see previous definition of 'ignoreSslErrors'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(224): warning C4273: 'SimpleMail::Sender::setPeerVerificationType': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(203): note: see previous definition of 'setPeerVerificationType'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(230): warning C4273: 'SimpleMail::Sender::peerVerificationType': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(209): note: see previous definition of 'peerVerificationType'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(236): warning C4273: 'SimpleMail::Sender::sendMail': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(211): note: see previous definition of 'sendMail'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(242): warning C4273: 'SimpleMail::Sender::lastError': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(213): note: see previous definition of 'lastError'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(248): warning C4273: 'SimpleMail::Sender::quit': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(215): note: see previous definition of 'quit'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(254): warning C4273: 'SimpleMail::Sender::socketStateChanged': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(218): note: see previous definition of 'socketStateChanged'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(258): warning C4273: 'SimpleMail::Sender::socketError': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(219): note: see previous definition of 'socketError'
2>D:\Dev\Cutelyst\simple-mail-master\src\sender.cpp(262): warning C4273: 'SimpleMail::Sender::socketReadyRead': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(220): note: see previous definition of 'socketReadyRead'
2>D:\Dev\Cutelyst\simple-mail-master\build\src\SimpleMail2Qt5_autogen\include_Release\moc_sender.cpp(144): warning C4273: 'SimpleMail::Sender::qt_static_metacall': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(32): note: see previous definition of 'qt_static_metacall'
2>D:\Dev\Cutelyst\simple-mail-master\build\src\SimpleMail2Qt5_autogen\include_Release\moc_sender.cpp(200): warning C4273: 'staticMetaObject': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(32): note: see previous definition of 'public: static QMetaObject const SimpleMail::Sender::staticMetaObject'
2>D:\Dev\Cutelyst\simple-mail-master\build\src\SimpleMail2Qt5_autogen\include_Release\moc_sender.cpp(200): error C2491: 'SimpleMail::Sender::staticMetaObject': definition of dllimport static data member not allowed
2>D:\Dev\Cutelyst\simple-mail-master\build\src\SimpleMail2Qt5_autogen\include_Release\moc_sender.cpp(211): warning C4273: 'SimpleMail::Sender::metaObject': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(32): note: see previous definition of 'metaObject'
2>D:\Dev\Cutelyst\simple-mail-master\build\src\SimpleMail2Qt5_autogen\include_Release\moc_sender.cpp(216): warning C4273: 'SimpleMail::Sender::qt_metacast': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(32): note: see previous definition of 'qt_metacast'
2>D:\Dev\Cutelyst\simple-mail-master\build\src\SimpleMail2Qt5_autogen\include_Release\moc_sender.cpp(224): warning C4273: 'SimpleMail::Sender::qt_metacall': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(32): note: see previous definition of 'qt_metacall'
2>D:\Dev\Cutelyst\simple-mail-master\build\src\SimpleMail2Qt5_autogen\include_Release\moc_sender.cpp(242): warning C4273: 'SimpleMail::Sender::smtpError': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(223): note: see previous definition of 'smtpError'
2>D:\Dev\Cutelyst\simple-mail-master\build\src\SimpleMail2Qt5_autogen\include_Release\moc_sender.cpp(249): warning C4273: 'SimpleMail::Sender::sslErrors': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\sender.h(224): note: see previous definition of 'sslErrors'
2>server.cpp
2>D:\Dev\Cutelyst\simple-mail-master\src\server.cpp(30): warning C4273: 'SimpleMail::Server::Server': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(69): note: see previous definition of '{ctor}'
2>D:\Dev\Cutelyst\simple-mail-master\src\server.cpp(38): warning C4273: 'SimpleMail::Server::~Server': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(70): note: see previous definition of '{dtor}'
2>D:\Dev\Cutelyst\simple-mail-master\src\server.cpp(43): warning C4273: 'SimpleMail::Server::host': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(75): note: see previous definition of 'host'
2>D:\Dev\Cutelyst\simple-mail-master\src\server.cpp(49): warning C4273: 'SimpleMail::Server::setHost': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(80): note: see previous definition of 'setHost'
2>D:\Dev\Cutelyst\simple-mail-master\src\server.cpp(55): warning C4273: 'SimpleMail::Server::port': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(85): note: see previous definition of 'port'
2>D:\Dev\Cutelyst\simple-mail-master\src\server.cpp(61): warning C4273: 'SimpleMail::Server::setPort': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(90): note: see previous definition of 'setPort'
2>D:\Dev\Cutelyst\simple-mail-master\src\server.cpp(67): warning C4273: 'SimpleMail::Server::hostname': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(95): note: see previous definition of 'hostname'
2>D:\Dev\Cutelyst\simple-mail-master\src\server.cpp(73): warning C4273: 'SimpleMail::Server::setHostname': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(101): note: see previous definition of 'setHostname'
2>D:\Dev\Cutelyst\simple-mail-master\src\server.cpp(79): warning C4273: 'SimpleMail::Server::connectionType': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(106): note: see previous definition of 'connectionType'
2>D:\Dev\Cutelyst\simple-mail-master\src\server.cpp(85): warning C4273: 'SimpleMail::Server::setConnectionType': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(111): note: see previous definition of 'setConnectionType'
2>D:\Dev\Cutelyst\simple-mail-master\src\server.cpp(93): warning C4273: 'SimpleMail::Server::username': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(116): note: see previous definition of 'username'
2>D:\Dev\Cutelyst\simple-mail-master\src\server.cpp(99): warning C4273: 'SimpleMail::Server::setUsername': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(121): note: see previous definition of 'setUsername'
2>D:\Dev\Cutelyst\simple-mail-master\src\server.cpp(108): warning C4273: 'SimpleMail::Server::password': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(126): note: see previous definition of 'password'
2>D:\Dev\Cutelyst\simple-mail-master\src\server.cpp(114): warning C4273: 'SimpleMail::Server::setPassword': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(131): note: see previous definition of 'setPassword'
2>D:\Dev\Cutelyst\simple-mail-master\src\server.cpp(120): warning C4273: 'SimpleMail::Server::authMethod': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(136): note: see previous definition of 'authMethod'
2>D:\Dev\Cutelyst\simple-mail-master\src\server.cpp(126): warning C4273: 'SimpleMail::Server::setAuthMethod': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(141): note: see previous definition of 'setAuthMethod'
2>D:\Dev\Cutelyst\simple-mail-master\src\server.cpp(132): warning C4273: 'SimpleMail::Server::sendMail': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(154): note: see previous definition of 'sendMail'
2>D:\Dev\Cutelyst\simple-mail-master\src\server.cpp(150): warning C4273: 'SimpleMail::Server::queueSize': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(161): note: see previous definition of 'queueSize'
2>D:\Dev\Cutelyst\simple-mail-master\src\server.cpp(156): warning C4273: 'SimpleMail::Server::connectToServer': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(168): note: see previous definition of 'connectToServer'
2>D:\Dev\Cutelyst\simple-mail-master\src\server.cpp(184): warning C4273: 'SimpleMail::Server::ignoreSslErrors': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(174): note: see previous definition of 'ignoreSslErrors'
2>D:\Dev\Cutelyst\simple-mail-master\src\server.cpp(193): warning C4273: 'SimpleMail::Server::ignoreSslErrors': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(180): note: see previous definition of 'ignoreSslErrors'
2>D:\Dev\Cutelyst\simple-mail-master\build\src\SimpleMail2Qt5_autogen\include_Release\moc_server.cpp(126): warning C4273: 'SimpleMail::Server::qt_static_metacall': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(31): note: see previous definition of 'qt_static_metacall'
2>D:\Dev\Cutelyst\simple-mail-master\build\src\SimpleMail2Qt5_autogen\include_Release\moc_server.cpp(154): warning C4273: 'staticMetaObject': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(31): note: see previous definition of 'public: static QMetaObject const SimpleMail::Server::staticMetaObject'
2>D:\Dev\Cutelyst\simple-mail-master\build\src\SimpleMail2Qt5_autogen\include_Release\moc_server.cpp(154): error C2491: 'SimpleMail::Server::staticMetaObject': definition of dllimport static data member not allowed
2>D:\Dev\Cutelyst\simple-mail-master\build\src\SimpleMail2Qt5_autogen\include_Release\moc_server.cpp(165): warning C4273: 'SimpleMail::Server::metaObject': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(31): note: see previous definition of 'metaObject'
2>D:\Dev\Cutelyst\simple-mail-master\build\src\SimpleMail2Qt5_autogen\include_Release\moc_server.cpp(170): warning C4273: 'SimpleMail::Server::qt_metacast': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(31): note: see previous definition of 'qt_metacast'
2>D:\Dev\Cutelyst\simple-mail-master\build\src\SimpleMail2Qt5_autogen\include_Release\moc_server.cpp(178): warning C4273: 'SimpleMail::Server::qt_metacall': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(31): note: see previous definition of 'qt_metacall'
2>D:\Dev\Cutelyst\simple-mail-master\build\src\SimpleMail2Qt5_autogen\include_Release\moc_server.cpp(196): warning C4273: 'SimpleMail::Server::smtpError': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(183): note: see previous definition of 'smtpError'
2>D:\Dev\Cutelyst\simple-mail-master\build\src\SimpleMail2Qt5_autogen\include_Release\moc_server.cpp(203): warning C4273: 'SimpleMail::Server::sslErrors': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\server.h(184): note: see previous definition of 'sslErrors'
2>serverreply.cpp
2>D:\Dev\Cutelyst\simple-mail-master\src\serverreply.cpp(21): warning C4273: 'SimpleMail::ServerReply::ServerReply': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\serverreply.h(31): note: see previous definition of '{ctor}'
2>D:\Dev\Cutelyst\simple-mail-master\src\serverreply.cpp(28): warning C4273: 'SimpleMail::ServerReply::~ServerReply': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\serverreply.h(32): note: see previous definition of '{dtor}'
2>D:\Dev\Cutelyst\simple-mail-master\src\serverreply.cpp(33): warning C4273: 'SimpleMail::ServerReply::error': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\serverreply.h(34): note: see previous definition of 'error'
2>D:\Dev\Cutelyst\simple-mail-master\src\serverreply.cpp(39): warning C4273: 'SimpleMail::ServerReply::responseCode': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\serverreply.h(36): note: see previous definition of 'responseCode'
2>D:\Dev\Cutelyst\simple-mail-master\src\serverreply.cpp(45): warning C4273: 'SimpleMail::ServerReply::responseText': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\serverreply.h(37): note: see previous definition of 'responseText'
2>D:\Dev\Cutelyst\simple-mail-master\src\serverreply.cpp(51): warning C4273: 'SimpleMail::ServerReply::finish': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\serverreply.h(43): note: see previous definition of 'finish'
2>D:\Dev\Cutelyst\simple-mail-master\build\src\SimpleMail2Qt5_autogen\include_Release\moc_serverreply.cpp(67): warning C4273: 'SimpleMail::ServerReply::qt_static_metacall': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\serverreply.h(28): note: see previous definition of 'qt_static_metacall'
2>D:\Dev\Cutelyst\simple-mail-master\build\src\SimpleMail2Qt5_autogen\include_Release\moc_serverreply.cpp(88): warning C4273: 'staticMetaObject': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\serverreply.h(28): note: see previous definition of 'public: static QMetaObject const SimpleMail::ServerReply::staticMetaObject'
2>D:\Dev\Cutelyst\simple-mail-master\build\src\SimpleMail2Qt5_autogen\include_Release\moc_serverreply.cpp(88): error C2491: 'SimpleMail::ServerReply::staticMetaObject': definition of dllimport static data member not allowed
2>D:\Dev\Cutelyst\simple-mail-master\build\src\SimpleMail2Qt5_autogen\include_Release\moc_serverreply.cpp(99): warning C4273: 'SimpleMail::ServerReply::metaObject': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\serverreply.h(28): note: see previous definition of 'metaObject'
2>D:\Dev\Cutelyst\simple-mail-master\build\src\SimpleMail2Qt5_autogen\include_Release\moc_serverreply.cpp(104): warning C4273: 'SimpleMail::ServerReply::qt_metacast': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\serverreply.h(28): note: see previous definition of 'qt_metacast'
2>D:\Dev\Cutelyst\simple-mail-master\build\src\SimpleMail2Qt5_autogen\include_Release\moc_serverreply.cpp(112): warning C4273: 'SimpleMail::ServerReply::qt_metacall': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\serverreply.h(28): note: see previous definition of 'qt_metacall'
2>D:\Dev\Cutelyst\simple-mail-master\build\src\SimpleMail2Qt5_autogen\include_Release\moc_serverreply.cpp(130): warning C4273: 'SimpleMail::ServerReply::finished': inconsistent dll linkage
2>d:\dev\cutelyst\simple-mail-master\src\serverreply.h(40): note: see previous definition of 'finished'
2>Generating Code...
2>Done building project "SimpleMail2Qt5.vcxproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by dantti** [comment]
please test master.

**Comment by Gisg22** [comment]
> please test master.

Master? What this? I'am just a beginner.

**Comment by dantti** [comment]
https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell#:~:text=The%20default%20branch%20name%20in,branch%20pointer%20moves%20forward%20automatically.&text=The%20%E2%80%9Cmaster%E2%80%9D%20branch%20in%20Git%20is%20not%20a%20special%20branch.

**Comment by Gisg22** [comment]
> [https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell#:~:text=The%20default%20branch%20name%20in,branch%20pointer%20moves%20forward % 20автоматически. & Text = The% 20% E2% 80% 9Cmaster% E2% 80% 9D% 20branch% 20in% 20Git% 20is% 20not% 20a% 20special% 20branch](https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell#:~:text=The%20default%20branch%20name%20in,branch%20pointer%20moves%20forward%20automatically.&text=The%20%E2%80%9Cmaster%E2%80%9D%20branch%20in%20Git%20is%20not%20a%20special%20branch) .

Thank you
