### ISSUE TITLE
How to compile this library in Windows

### ISSUE THREAD

**Issue by hkottmann** [cutelyst/simple-mail#35]
I was able to compile and use this library on my Linux box, but on Windows I'm not able to compile this library. I have used QTCreator which is capable to deal with CMake-files but during the compiling process I've got first tons of such warnings:

C:\Users\kottmann_h\Documents\QT\simple-mail-master\src\emailaddress.cpp:22: warning: 'SimpleMail::EmailAddress::EmailAddress()' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
 EmailAddress::EmailAddress() : d_ptr(new EmailAddressPrivate)

and at the end tons of such linker errors:

C:\Users\kottmann_h\Documents\QT\simple-mail-master\src\emailaddress.cpp:22: error: undefined reference to `__imp__ZTVN10SimpleMail12EmailAddressE'

The library upon which this library is based on I was able to compile, but it was not working:

https://github.com/bluetiger9/SmtpClient-for-Qt

**Comment by dantti** [comment]
Please test

**Comment by hkottmann** [comment]
It's working well, thank you for your help
