### ISSUE TITLE
Releasing 2.0.1 

### ISSUE THREAD

**Issue by zgyarmati** [cutelyst/simple-mail#37]
I'm about to package simple-mail for [msys2](https://github.com/msys2/MINGW-packages), and i hit the build issue which is already fixed by ff84c2d. Would it be possible to make a point release with this fix, so i can avoid patching at downstream?

**Comment by dantti** [comment]
sure, will do it soon.

**Comment by dantti** [comment]
done, did a 2.1 as I renamed a header that referenced the old name of this lib
