### ISSUE TITLE
Erros in async1.cpp

### ISSUE THREAD

**Issue by Loclay** [cutelyst/simple-mail#38]
/home/user/simple-mail/demos/async1/async1.cpp:22:105: error: incorrect converting from «const char*» в «int» [-fpermissive]
message.setSender(SimpleMail::EmailAddress(QLatin1String("your_email_address@gmail.com", "Your Name")));

I changed "Your Name" to a number, and compilation ended without errors.

I'm not a programmer, I can't check where I closing parenthesis.

**Comment by dantti** [comment]
Ah now I noticed that this was on one of the demos, it's fixed in master.
Thanks
