### ISSUE TITLE
Update the manual/readme and/or pro file

### ISSUE THREAD

**Issue by Beginner-2** [cutelyst/simple-mail#41]
Hallo,

compiling under Linux was easy. It compiled the libary and all examples very nicely just by 2 commands. Maybe add them into the readme:
cmake CMakeLists.txt
make

But i am not clever enough to do that also with Windows. I tried with gcc/mingw, but cmake doesn't run with it.
I tried mvs. then "cmake CMakeLists.txt" works fine, but not make. i also tried nmake.

Maybe someone can write a hint into the readme how to do it with Windows and MacOS?
Or maybe even better: Someone can add a .pro file, so we can use qmake independently on every os with all compilers very easy. maybe at least for the library.

Thank you!

**Comment by dantti** [comment]
cmake CMakeLists.txt is a wrong command, you just need to specify the path where the sources are.
On Windows it might be easier to setup with VCPKG, there are tons of examples on how to use it on Windows, MacOS with brew is also very easy.
About .pro well qmake is dying so I don't care about it.

**Comment by dantti** [comment]
https://cmake.org/runningcmake/

**Comment by Beginner-2** [comment]
Thank you!
yes, "cmake ./" is fine already.
I was so stupid and worked always on command line (or tried with MS Studio and cmake-gui), but it is so easy:
Just open the CMakeLists.txt with QtCreator.
All fine. It compiles the samples, the dll with MinGW and mvs. Both with 32 and 64 bit.
Perfekt.
Thank you!

So if i link the dll file to my project i also want to add a note that i use that dll file (and care of course about the other LGPL-stuff).
For Qt I wrote for example "Qt 5.15.0: (c) The Qt Company. https//www.qt.io/".
So what should i write here:
"SimpleMail2Qt5: (c) Tőkés Attila. https://github.com/cutelyst/simple-mail/" ? Or something different?

**Comment by dantti** [comment]
SimpleMail was written by many people, in fact it's a fork from SMTPClient which Tőkés Attila wrote,
I think just SimpleMailQt and a link to github is fine
