### ISSUE TITLE
compile error in Qt 5.15.1

### ISSUE THREAD

**Issue by hexabyte23** [cutelyst/simple-mail#44]
I get compile error in sender.cpp & server.cpp

../rcs/thirdparty/simple-mail/src/sender.cpp:148:24: error: static_cast from 'QAbstractSocket::SocketError (QAbstractSocket::*)() const' to 'void (QTcpSocket::*)(QTcpSocket::SocketError)' is not allowed
    connect(d->socket, static_cast<void(QTcpSocket::*)(QTcpSocket::SocketError)>(&QTcpSocket::error),
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../rcs/thirdparty/simple-mail/src/server.cpp:237:24: error: static_cast from 'QAbstractSocket::SocketError (QAbstractSocket::*)() const' to 'void (QTcpSocket::*)(QTcpSocket::SocketError)' is not allowed
    q->connect(socket, static_cast<void(QTcpSocket::*)(QTcpSocket::SocketError)>(&QTcpSocket::error),
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by dantti** [comment]
which Qt version/compiler are you using?

**Comment by dantti** [comment]
duh 5.15, well that's odd I didn't try with that version but is should work afaik

**Comment by hexabyte23** [comment]
Since 5.14.2, Qt is no more allowed to use static_cast<void(QTcpSocket::*)(QTcpSocket::SocketError)> in connect(), I try to replace by 

```
    q->connect(socket, static_cast<void(QTcpSocket::*)(QTcpSocket::SocketError)>(&QTcpSocket::error),
               q, [=] (QAbstractSocket::SocketError error) {...}
```

by

```
    q->connect(socket, &QAbstractSocket::errorOccurred,
               q, [=] (QAbstractSocket::SocketError error) {...}

```
but I introduce an infinite loop when error occur by doing so... inner change in Qt seems larger

**Comment by dantti** [comment]
From Qt docs errorOccurred was introduced in 5.15, where do you get an infinite loop?

**Comment by dantti** [comment]
ping?

**Comment by hexabyte23** [comment]
Sorry, I get infinite loop inside function sendMail() during call server->sendMail(message), only in Qt5.15.1 version

**Comment by dantti** [comment]
can you grab a backtrace?

**Comment by hexabyte23** [comment]
Quite difficult now to get back my old code, you don't succeed to have same issue ?

**Comment by dantti** [comment]
I still don't have 5.15 installed, but did you managed to work around the issue? or are using an older Qt?

**Comment by hexabyte23** [comment]
no, I found another way to send mail by using sendmail() unix command directly 

```
   QProcess sendMail;
   sendMail.setStandardInputFile(file.fileName());
   sendMail.start("sendmail", QStringList() << "-t");
   sendMail.waitForFinished();

```

**Comment by dantti** [comment]
Pushed fix
