### ISSUE TITLE
How to check login credentials before sending mail

### ISSUE THREAD

**Issue by useful-friend** [cutelyst/simple-mail#46]
How can I check login credentials before sending an email? is it possible at all?

**Comment by dantti** [comment]
sorry but can you elaborate your question?

**Comment by useful-friend** [comment]
Assume you enter username and password and the host and port in a GUI form. Is there any way to check that the entered values are valid without sending any emails? checking both the connection and the authentication? maybe a `bool login()` function?
I want to save those values and use them later in the application and I want to show errors on the same page if the above values are not valid, so the user can change them without the need to test them inside the application.

**Comment by dantti** [comment]
there is https://github.com/cutelyst/simple-mail/blob/master/src/server.h#L168
but only failed signals are emitted, you can do a PR adding one authenticated() or so

**Comment by dantti** [comment]
Waiting for PR
