### ISSUE TITLE
How to Install this

### ISSUE THREAD

**Issue by BrickleRex** [cutelyst/simple-mail#48]
Hi there. I cant find a singular straight forward guide as to how to install/use this library in my Qt C++ project. I'd appreciate it if you could help me out.

**Comment by dantti** [comment]
It's a CMake based project so same commands as usual, cmake && make && make install.. of course you might need to tweak some CMake options depending on your platform

**Comment by BrickleRex** [comment]
How would I go about installing this within Qt Creator. I'd appreciate it if you could provide step by step instructions on this. I'm new to all this. Thanks.

**Comment by dantti** [comment]
Open the CMakeLists.txt project on QtCreator, tell it to compile, then on your project point it to the compiled thing, or just download the provided .deb or see if your distro has it packaged

**Comment by BrickleRex** [comment]
If I download the .deb, how do I use it on my Qt Program?

**Comment by dantti** [comment]
add
find_package(SimpleMail2Qt5 2.0.0 REQUIRED)
to your CMakeLists.txt and link like the examples
https://github.com/cutelyst/simple-mail/blob/master/demos/async1/CMakeLists.txt

**Comment by BrickleRex** [comment]
I'm getting the following error:

CMake Error at CMakeLists.txt:72 (set_target_properties):
  set_target_properties called with incorrect number of arguments.

Should I add the find_package statement at the end of the CMakeLists.txt file or at the beginning?

**Comment by dantti** [comment]
at the begging, I suggest you
to read some CMake tutorial like
https://cmake.org/cmake/help/latest/guide/tutorial/index.html
or 
https://www.jetbrains.com/help/clion/quick-cmake-tutorial.html
as this isn't an issue of simple mail

**Comment by DavidKelleySCSC** [comment]
I Presume what you really want is a **Qt pro** file to use.  Qt can create these as mentioned above, but I always seem to have issues using that.  

I recently start to re-use this code and had to do that same thing.  We had been using it as a DLL, before but I wanted it all in-line so I could tweak a few issue we had (and also could debug better).    To create the Qt Pro file open up whatever core project you plan to use this with (or a generic Qt GUI window).  Add every file you see (in the Qt project, right click on _add existing files..._ and select everything you see, Qt will sort it out.).  You might want to place these files in their own folder (/mail in the below example). Your pro file will have include lines like this now:

```
    mail/emailaddress.h \
    mail/mimeattachment.h \
    mail/mimecontentformatter.h \
    mail/mimefile.h \
    mail/mimehtml.h \
    mail/mimeinlinefile.h \
    mail/mimemessage.h \
    mail/mimemultipart.h \
    mail/mimepart.h \
    mail/mimetext.h \
    mail/quotedprintable.h \
    mail/smtpclient.h \
    mail/smtpexports.h
```
And there will be something similar for the cpp files.  Almost done.  Now go to the file **smptexport.h** and modify it to remove the DLL tags as shown below.  [I am presuming  here that you do not want a DLL, at least to start with.]  

```
#ifndef SMTPEXPORTS_H
#define SMTPEXPORTS_H

// Not used or required when not a DLL
//#ifdef SMTP_BUILD
//#define SMTP_EXPORT Q_DECL_EXPORT
//#else
//#define SMTP_EXPORT Q_DECL_IMPORT
//#endif
// Instead, use a blank line so does not invoke DLLL exporting
#define SMTP_EXPORT

#endif // SMTPEXPORTS_H

```
You can now compile and run this.  Perhaps the easiest way to start is to take one the demos and paste it into your mainwindow start routine.  In our use case we built up another class to handle the calls and while the whole pile is part of the project, only that class is exposed to other.  Hope this is helpful.

**Comment by dantti** [comment]
Qt 6 is deprecating qmake, learning how to properly use CMake will pay you not only in future but also now.
Also instead of building as a dynamic library you can tell CMake to build it as static library and simply import the resulting object file your project.

**Comment by BrickleRex** [comment]
> I Presume what you really want is a **Qt pro** file to use. Qt can create these as mentioned above, but I always seem to have issues using that.
> 
> I recently start to re-use this code and had to do that same thing. We had been using it as a DLL, before but I wanted it all in-line so I could tweak a few issue we had (and also could debug better). To create the Qt Pro file open up whatever core project you plan to use this with (or a generic Qt GUI window). Add every file you see (in the Qt project, right click on _add existing files..._ and select everything you see, Qt will sort it out.). You might want to place these files in their own folder (/mail in the below example). Your pro file will have include lines like this now:
> 
> ```
>     mail/emailaddress.h \
>     mail/mimeattachment.h \
>     mail/mimecontentformatter.h \
>     mail/mimefile.h \
>     mail/mimehtml.h \
>     mail/mimeinlinefile.h \
>     mail/mimemessage.h \
>     mail/mimemultipart.h \
>     mail/mimepart.h \
>     mail/mimetext.h \
>     mail/quotedprintable.h \
>     mail/smtpclient.h \
>     mail/smtpexports.h
> ```
> 
> And there will be something similar for the cpp files. Almost done. Now go to the file **smptexport.h** and modify it to remove the DLL tags as shown below. [I am presuming here that you do not want a DLL, at least to start with.]
> 
> ```
> #ifndef SMTPEXPORTS_H
> #define SMTPEXPORTS_H
> 
> // Not used or required when not a DLL
> //#ifdef SMTP_BUILD
> //#define SMTP_EXPORT Q_DECL_EXPORT
> //#else
> //#define SMTP_EXPORT Q_DECL_IMPORT
> //#endif
> // Instead, use a blank line so does not invoke DLLL exporting
> #define SMTP_EXPORT
> 
> #endif // SMTPEXPORTS_H
> ```
> 
> You can now compile and run this. Perhaps the easiest way to start is to take one the demos and paste it into your mainwindow start routine. In our use case we built up another class to handle the calls and while the whole pile is part of the project, only that class is exposed to other. Hope this is helpful.

Thanks for your help. I think I'm mostly done. Just the following error. Can you help?

fatal error: QSslSocket: No such file or directory

I have installed Openssl x64 for windows. I did add it as a library into my project. What else must I do?

**Comment by DavidKelleySCSC** [comment]
In you project (pro file) make sure to have:
QT    += network

**Comment by BrickleRex** [comment]
Ah ok. Thank you for your help. It finally compiled. I'll ask you if I need any more assistance. Thanks for everything.

**Comment by BrickleRex** [comment]
Just one last thing. There's an error occurring with the SSL handshake. Here it is:

ServerReply finished true "Error during SSL handshake: error:1408F10B:SSL routines:ssl3_get_record:wrong version number"

I used "smpt.live.com" as my smtp server, an SSLConnection type, with port 587. Is there something I'm missing?

**Comment by BrickleRex** [comment]
Just one last thing. There's an error occurring with the SSL request. Here it is:

simplemail.sender: Sending MAIL 0x6280240
simplemail.sender: Processing state 1
simplemail.sender: Connecting to host encrypted "smtp.live.com" 587
simplemail.sender: Response timed out
Failed to send mail! "Response timed out"
QIODevice::write (QSslSocket): device not open
QIODevice::write (QSslSocket): device not open

I used "smpt.live.com" as my smtp server, an SSLConnection type, with port 587. Is there something I'm missing?

**Comment by dantti** [comment]
It seems they don't use SSL but rather TLS (STARTTLS)

**Comment by BrickleRex** [comment]
Is it better if I use tlsconnection type?

**Comment by dantti** [comment]
This is not about better or worse, it's about what the server supports

**Comment by BrickleRex** [comment]
Yes I used TlsConnectionType and it progressed. It still times out, but it goes further.

simplemail.sender: Sending MAIL 0x6fa7880
simplemail.sender: Processing state 1
simplemail.sender: Connecting to host "smtp.live.com" 587
simplemail.sender: Got response "220 AM0PR01CA0168.outlook.office365.com Microsoft ESMTP MAIL Service ready at Mon, 7 Dec 2020 22:21:48 +0000"
simplemail.sender: Sending EHLO "LAPTOP-O5DN1238"
simplemail.sender: Got response "250-AM0PR01CA0168.outlook.office365.com Hello [2001:16a2:b405:7800:b9f7:41cb:c0ae:8ba0]"
simplemail.sender: Got response "250-SIZE 157286400"
simplemail.sender: Got response "250-PIPELINING"
simplemail.sender: Got response "250-DSN"
simplemail.sender: Got response "250-ENHANCEDSTATUSCODES"
simplemail.sender: Got response "250-STARTTLS"
simplemail.sender: Got response "250-8BITMIME"
simplemail.sender: Got response "250-BINARYMIME"
simplemail.sender: Got response "250-CHUNKING"
simplemail.sender: Got response "250 SMTPUTF8"
simplemail.sender: Sent hello
simplemail.sender: Sending STARTTLS
simplemail.sender: Got response "220 2.0.0 SMTP server ready"
simplemail.sender: Starting client encryption
simplemail.sender: Sending second EHLO "LAPTOP-O5DN1238"
simplemail.sender: Got response "250-AM0PR01CA0168.outlook.office365.com Hello [2001:16a2:b405:7800:b9f7:41cb:c0ae:8ba0]"
simplemail.sender: Got response "250-SIZE 157286400"
simplemail.sender: Got response "250-PIPELINING"
simplemail.sender: Got response "250-DSN"
simplemail.sender: Got response "250-ENHANCEDSTATUSCODES"
simplemail.sender: Got response "250-AUTH LOGIN XOAUTH2"
simplemail.sender: Got response "250-8BITMIME"
simplemail.sender: Got response "250-BINARYMIME"
simplemail.sender: Got response "250-CHUNKING"
simplemail.sender: Got response "250 SMTPUTF8"
simplemail.sender: Processing state 2
simplemail.sender: Sending authentication plain
simplemail.sender: Response timed out
Failed to send mail! "Response timed out"

**Comment by dantti** [comment]
I don't have an account there to test, you can try using the ASync version to see if there are any differences.

**Comment by BrickleRex** [comment]
When I use Async version, the following happens:

If I use SSLConnection type then, i get this, "ServerReply finished true "Error during SSL handshake: error:1408F10B:SSL routines:ssl3_get_record:wrong version number"

If I use TLSConnection type then, i get this, "simplemail.server: Unexpected server response "504 5.7.4 Unrecognized authentication type [AM4P190CA0011.EURP190.PROD.OUTLOOK.COM]" 235"

What seems to be the problem?

**Comment by dantti** [comment]
this seems to be the wrong auth method try changing setAuthMethod()

**Comment by dantti** [comment]
simplemail.sender: Got response "250-AUTH LOGIN XOAUTH2"

From the response you need to use the LOGIN auth method.

**Comment by BrickleRex** [comment]
I just used the Gmail SMTP server so now it's working. Thanks for all your help.

**Comment by BrickleRex** [comment]
P.S Do not close the issue yet. I may yet require assistance.

**Comment by DavidKelleySCSC** [comment]
I found it useful to instrument the code up a bit more to help me learn, lots of small bits like this one, passes back the problem to the caller and to qDebug.  I am not a SMTP expert, but our mail server is only a few yards away and that helps to see the exchange from both sides.  

```
    // Tries to connect to server
    if (!socket->waitForConnected(connectionTimeout))
    {
        emit smtpError(ConnectionTimeoutError);
        *replyStr = (QObject::tr("eMail-a, %1<br>&nbsp;&nbsp;Error reply %2:%3")
                     .arg(responseText)
                     .arg(socket->error())
                     .arg(socket->errorString()));
        qDebug() << *replyStr;
        return false;
    }
```

**Comment by BrickleRex** [comment]
Thanks for the suggestion! I have one last problem. The program apparently stops execution after sending the mail, though I do not specify this in my code. Why is this happening, and what can I do about it?

**Comment by dantti** [comment]
Impossible to tell without seeing your code.
