### ISSUE TITLE
Crash on blocking example (Windows, Qt5.12.4, MSVC)

### ISSUE THREAD

**Issue by LangeSebastian** [cutelyst/simple-mail#51]
Hi (again),

Sender.SendMail does not seem to be blocking therefore deletes the referred parts with qDeleteAll(parts), whereas we still require it. This happens when 'Sender' OR 'Message' go out of scope before mail is actually done sending.

`MimeMultiPartPrivate::~MimeMultiPartPrivate()
{
    qDeleteAll(parts);
}`

It works when changing to pointers instead of references. 

On a side note to qDeleteAll(): We just had to many issues related to these meta clearing container macros/functions that we just replaced all qDelete*() calls with custom loop + take/delete.

**Comment by dantti** [comment]
Yes, it's known issue with the examples, indeed they cannot be local objects otherwise when leaving scope they will crash..

**Comment by LangeSebastian** [comment]
Ok. Thank you.

We will just change our application using pointers. You may want to change the readMe and remove/comment the blocking example.
