### ISSUE TITLE
Mutliple mime attechments of the same type not sending

### ISSUE THREAD

**Issue by DavidKelleySCSC** [cutelyst/simple-mail#52]
Is there any reason that Multiple mime attachments of the same type (in this case text/html) would not work in _simple-mail_ or due to some RFC spec detail?   I see the example with multiple images in Demo4, and I understand that that a common email mode is to have a text attachment and an html attachment, with the client then showing one or the other.  But are we not allowed to append N MimeHtml objects along with any other arbitrary content?   

When I have more than one html part, then 2nd one onwards is never shown.  I have managed to get a workaround to go by creating a single master html instance and including all other content within that. But in this application different parts of content come from different parts of the app and are less easily merged (and from another thread, we would have to keep the unique content created around at a memory cost).  After a long day I am not sure about my code not being at fault, but is there any reason one could not have, say, five separate html attachments in a sequence in the email?

**Comment by DavidKelleySCSC** [comment]
Bump. To repeat; is there any reason one cannot have multiple html mime attachments in the same email message?

**Comment by dantti** [comment]
you can have how many do you want, but the mail client will need to choose one, I think this question is not related to simple mail, unless you see the mail packet is not sending them all

**Comment by DavidKelleySCSC** [comment]
Just to update before closing, simple-mail is doing it all fine, and the std appears to allow many, but the common convention is that client side (mail client in this case) will only show a subset (limited testing show the first).  We ended up reworking the flow of things to place everything into one master html mine attachment which just cost some memory and copy operations.
