### ISSUE TITLE
simple-mail  vs SmtpClient-for-Qt

### ISSUE THREAD

**Issue by DavidKelleySCSC** [cutelyst/simple-mail#53]
Can we get a short summary of how  **cutelyst / simple-mail**  is related to the older project  **bluetiger9 /  SmtpClient-for-Qt**   and/or any other primary sources used?  
Trying the get our legal folks satisfied about the code ownership and its history.

**Comment by dantti** [comment]
I forked that project, add CMake to it, fixed several stuff, made it look like a real library, and recently I added async support.
Since I like LGPL and the original license was that it still LGPL

**Comment by DavidKelleySCSC** [comment]
Perfect, thanks for the quick reply, that will keep 'em happy.   (and LGPL works here)
Caution do not link to if you still have work to do today: http://www.iciclesoftware.com/LawJokes/IcicleLawJokes.html
