### ISSUE TITLE
Issues with Async example

### ISSUE THREAD

**Issue by DavidKelleySCSC** [cutelyst/simple-mail#54]
There seems to be a lot of places in the async1.cpp example where you are depending on a space between the the response code and the rest of the response string  ` if (responseText[3] == ' ') ...     `

Our server (made by Icewarp) replies with a space at times and at other times with "-" and the above logic will not work.  
As in: "250-Node.xxxxx.net Hello YYYY [xx.xx.xx.xx], pleased to meet you."

My first thought is to go in and replace the above logic with  ` if ((responseText[3] == ' ') || (responseText[3] == '-')) {`
Is there a semantic meaning to the use of "-" that this would disturb?

**Comment by dantti** [comment]
from my research this is related to multiline response, https://tools.ietf.org/html/rfc2920
Basicaly the last response line must NOT have a dash, but I'm not sure how to handle this case.

**Comment by DavidKelleySCSC** [comment]
I cannot say that I understand the cause and effect here, but by tweaking some setting on our SMTP server, and tinkering with one that we lease (rackspace), the problem seems to be gone.  My hunch is that this is also related the disabling TLS and SSL for testing which may have produced odd results.   So I am marking it as closed, but I may still use the above patch as I so far see no harm.
