### ISSUE TITLE
error: C2139: QSslError: undefined class is not allowed as an argument in the compiler internal type characteristic "__is_base_of"

### ISSUE THREAD

**Issue by Gisg22** [cutelyst/simple-mail#72]
I included all the files in my project, but this error occurred.I tried to include a lib on Windows. What needs to be done to make it work?

**Comment by Gisg22** [comment]
Then, there is a second error: QtPrivate :: QDataStreamOperatorForType: too few arguments pattern

**Comment by dantti** [comment]
Sorry no idea I don't use Windows.

**Comment by Gisg22** [comment]
> Sorry no idea I don't use Windows.

it's a pity.

**Comment by Gisg22** [comment]
Somehow it worked for me. Messages are sent, but a very strange problem arises that only those using Windows can figure out.

**Comment by FalsinSoft** [comment]
I develop under Windows. Just pulled a merge request fixing this issue.

**Comment by dantti** [comment]
Basic support for when Qt is built without SSL support was pushed
