### ISSUE TITLE
Cleaning Up - Ownership?

### ISSUE THREAD

**Issue by HymiR** [cutelyst/simple-mail#8]
In the demos, you often use following statement:
`MimeAttachment document(new QFile(QLatin1String("document.pdf")));`

Does the MimeAttachment care about deleting the QFile instance?
Or do I have to call file.deleteLater() ?

Thank you and greetings from Austria.

**Comment by dantti** [comment]
Yup, here: https://github.com/cutelyst/simple-mail/blob/master/src/mimepart.cpp#L333

**Comment by HymiR** [comment]
Thank you very much!

In demo2 there's a similar statement:
```
    for (int i = 0; i < ui->attachments->count(); ++i)
    {
        message.addPart(new MimeAttachment(new QFile(ui->attachments->item(i)->text())));
    }
```

Is this also true for MimeMultipart types, like here, adding attachment or if you use:
`message.setContent(new MimeMultipart(MimeMultipart::Mixed));`

Deleting such an attachment or self-created content causes the application to crash.
I skimmed the code but didn't find something helpful.
Sorry for the inconvenience and thanks in advance.

**Comment by dantti** [comment]
Yes they are all derived of the same class, for 2.0 I plan to replace the sever with an async API, and maybe I replace these stuff with QPointer to avoid crashing.

**Comment by HymiR** [comment]
All right, thank you very much.
