### ISSUE TITLE
Blocking code crashes after code block finishes

### ISSUE THREAD

**Issue by joshorenberg** [cutelyst/simple-mail#80]
I am running Qt Created based on Qt 5.15.2. The blocking code crashes after the code block completes. The email sends successfully. I borrowed code from the example and modified it. Application output is Critical error detected c0000374. Here is the backtrace:

![backtrace cl](https://user-images.githubusercontent.com/22732423/186064437-5bcbb7df-5c4a-410d-a748-a24042ea76d7.png)

Thanks!

**Comment by dantti** [comment]
no clue without seeing actual code, or a minimal code that crashes

**Comment by joshorenberg** [comment]
Here 'tis, a little stripped for the relevant parts only. The situation I've been testing is with a multimap with only one key value pair and the program crashes when exiting the inner code block. Thanks!

```
void Program::sendEmails()
{
    QMultiMap<QString,BackupJob>::const_iterator iterator = emailAddressMultiMap.constBegin();
    while (iterator != emailAddressMultiMap.constEnd())
    {
        messageString += ... //construct the string here

        SimpleMail::Sender sender("smtp.***.com", 465, SimpleMail::Sender::SslConnection);

        sender.setUser("address@***.com");
        sender.setPassword("password");

        SimpleMail::MimeMessage message;
        message.setSender(SimpleMail::EmailAddress("from@from.com", "Program"));
        message.addTo(SimpleMail::EmailAddress(iterator.key()));
        message.setSubject("Email");

        SimpleMail::MimeText text;
        text.setText(messageString);
        message.addPart(&text);

        sender.sendMail(message); // Blocks untill mail is delivered or errored
        //qDebug() << sender.responseText();
        sender.quit();

        QString emailAddress = iterator.key();
        while (iterator != emailAddressMultiMap.constEnd() && iterator.key() == emailAddress)
            ++iterator;
    }
}
```

**Comment by dantti** [comment]
addPart() takes ownership of part so it will crash as it get's deleted twice.

**Comment by joshorenberg** [comment]
How to remedy?

**Comment by joshorenberg** [comment]
Still getting the same crash, new backtrace:

![backtrace cl2](https://user-images.githubusercontent.com/22732423/186263116-22db4b34-b251-4df4-a348-57622e2afb49.png)

**Comment by joshorenberg** [comment]
I found a workaround for the error... I offloaded the email sending code to a worker thread (which is what I wanted in the first place) and everything is working now, no more crashes. Weird...
