### ISSUE TITLE
comma in name (part of email address) is not handled correctly (it seams)

### ISSUE THREAD

**Issue by eightdot** [cutelyst/simple-mail#85]
calling 
```
SimpleMail::Sender sender;
SimpleMail::MimeMessage message;
message.addTo(SimpleMail::EmailAddress("user@example.org", "surname, forename"));
sender.sendMail(message);

```
results in the following to header:
`To: surname, forename <user@example.org>`

which should have been quoted or escaped afaick.

i tested with 

`python -m smtpd -n -c DebuggingServer 127.0.0.1:25`

**Comment by dantti** [comment]
Just did a test and worked fine like this.
