### ISSUE TITLE
Provide GPL license exclusion

### ISSUE THREAD

**Issue by FatBrownDog** [cutelyst/simple-mail#88]
Hi,
Since the author provided Patreon, what is the cost or price for licensing this project under non-GPL?

For example, like some authors such clause:
https://github.com/fnc12/sqlite_orm
"The project has AGPL license for open source project and MIT license after purchasing it for 50$"

**Comment by dantti** [comment]
Patreon was to support not to purchase different licenses, since the async version is mostly a rewrite I was planning to do a V3 where I rewrite the rest of it and relicense as MIT, but I don't have much time to work on this ATM.

**Comment by FatBrownDog** [comment]
Let me know when v3 is ready. You can make good money with a paid MIT license version. :).
