### ISSUE TITLE
Can not send email when bcc is used

### ISSUE THREAD

**Issue by timotheux** [cutelyst/simple-mail#9]
Hi,

Let me start by saying you have done a tremendous job with this library.

I have been testing it for a while and found that it works well until i tried using the bcc function.
It failed at:
`if (!smtp.sendMail(message)) {

        qDebug() << "Failed to send mail!" << endl;
        return -3;
    }`

when i use:
`if(bccSender) {

        EmailAddress bcc(fromEmail, fromName);
        message.addBcc(&bcc);
    }`

I am sending thru gmail on windows 10 with Qt 5.9.1 dynamic build. I also have openssl installed.

Thanks

**Comment by dantti** [comment]
Can you try to debug a little more to see why it returns false? I'm a little busy ATM to investigate the issue

**Comment by dantti** [comment]
closing as didn't get any feedback and I've just tested and it works for me
