### ISSUE TITLE
MimeAttachment

### ISSUE THREAD

**Issue by hernanre** [cutelyst/simple-mail#95]
I am trying to add an attachment to an email. However, when I use the addPart() and pass in the attachment I get a double free or corruption (out) function. Multiple projects are having this same error. 
`SimpleMail::MimeAttachment attachment(new QFile(QLatin1String("/path/to/attachment")));

   // the file type can be setted. (by default is application/octet-stream)
   attachment.setContentType(QByteArrayLiteral("image/jpg"));

   //Now add it to message

   message.addPart(&attachment);`
Has this been resolved?

**Comment by dantti** [comment]
Yes, use the API with smart pointers

**Comment by baliloo** [comment]
Hi, 
same problem even with smart pointer !!!
