### ISSUE TITLE
addPart crashes !!!

### ISSUE THREAD

**Issue by baliloo** [cutelyst/simple-mail#98]
Hi, 
`auto text = std::make_shared<SimpleMail::MimeText>();
text->setText(QLatin1String("Hi,\nThis is a simple email message.\n"));
message.addPart(text);`

 addPart method keep crashing ....

**Comment by fverneau** [comment]
Hi,
I confirm, I have exactly the same problem. AddPart crash (Qt 6.7.2 with MSVC2019 64 bits)

**Comment by dantti** [comment]
please test current master, there's a potential fix

**Comment by fverneau** [comment]
I downloaded the new version of the Master. I was able to recompile the library with Qt 6.7.2 and MSVC2019 64-bit.
Adding content to the email works fine now.
Everything seems to be back to normal.
Many thanks for this fix !
