### ISSUE TITLE
Example/demo projects segfault

### ISSUE THREAD

**Issue by karmicthreat** [cutelyst/simple-mail#99]
Taken from my app. But the same issue is in all the examples as well.
Backtrace
* thread #12, name = 'EmailSchedulerThread', stop reason = EXC_BAD_ACCESS (code=1, address=0x80)
  * frame #0: 0x0000000100dbba20 libSimpleMail3Qt6.0.dylib`void qt_ptr_swap<QTypedArrayData<char>>(lhs=0x0000000000000080, rhs=0x000070000f3b3420) at qswap.h:31:14
    frame #1: 0x0000000100dbb9d1 libSimpleMail3Qt6.0.dylib`QArrayDataPointer<char>::swap(this=0x0000000000000080, other=0x000070000f3b3420) at qarraydatapointer.h:131:9
    frame #2: 0x0000000100dbb99d libSimpleMail3Qt6.0.dylib`QByteArray::swap(this=0x0000000000000080, other=0x000070000f3b3420) at qbytearray.h:103:9
    frame #3: 0x0000000100dbb541 libSimpleMail3Qt6.0.dylib`QByteArray::operator=(this=0x0000000000000080, other=0x000070000f3b3420) at qbytearray.h:101:5
    frame #4: 0x0000000100dcd905 libSimpleMail3Qt6.0.dylib`SimpleMail::MimePart::MimePart(this=0x000070000f3b34d0, other=0x0000600003598df8) at mimepart.cpp:37:23
    frame #5: 0x0000000100dcdeed libSimpleMail3Qt6.0.dylib`SimpleMail::MimePart::MimePart(this=0x000070000f3b34d0, other=0x0000600003598df8) at mimepart.cpp:35:1
    frame #6: 0x0000000100dbeffc libSimpleMail3Qt6.0.dylib`SimpleMail::MimeMessage::addPart(this=0x000070000f3b36c0, part=std::__1::shared_ptr<SimpleMail::MimePart>::element_type @ 0x00006000035987f8 strong=2 weak=1) at mimemessage.cpp:195:20
    frame #7: 0x000000010020c95a clxboosted`EmailScheduler::sendEmailWithAttachment(this=0x000070000f3b3f28, filePath=0x000070000f3b3818) at emailscheduler.cpp:96:13
    frame #8: 0x000000010020c0ef clxboosted`EmailScheduler::checkAndSendEmail(this=0x000070000f3b3f28) at emailscheduler.cpp:39:9
    frame #9: 0x000000010020d124 clxboosted`QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (EmailScheduler::*)()>::call(f=(clxboosted`EmailScheduler::checkAndSendEmail() at emailscheduler.cpp:22), o=0x000070000f3b3f28, arg=0x000070000f3b3ab0) at qobjectdefs_impl.h:145:13
    frame #10: 0x000000010020d05d clxboosted`void QtPrivate::FunctionPointer<void (EmailScheduler::*)()>::call<QtPrivate::List<>, void>(f=(clxboosted`EmailScheduler::checkAndSendEmail() at emailscheduler.cpp:22), o=0x000070000f3b3f28, arg=0x000070000f3b3ab0) at qobjectdefs_impl.h:182:13
    frame #11: 0x000000010020cf75 clxboosted`QtPrivate::QCallableObject<void (EmailScheduler::*)(), QtPrivate::List<>, void>::impl(which=1, this_=0x0000600003b8d3e0, r=0x000070000f3b3f28, a=0x000070000f3b3ab0, ret=0x0000000000000000) at qobjectdefs_impl.h:553:21
    frame #12: 0x0000000102e49b3f QtCore`void doActivate<false>(QObject*, int, void**) [inlined] QtPrivate::QSlotObjectBase::call(this=0x0000600003b8d3e0, r=0x000070000f3b3f28, a=0x000070000f3b3ab0) at qobjectdefs_impl.h:469:51 [opt]
    frame #13: 0x0000000102e49b2a QtCore`void doActivate<false>(sender=0x00006000039e9a50, signal_index=3, argv=0x000070000f3b3ab0) at qobject.cpp:4086:26 [opt]
    frame #14: 0x0000000102e5d36a QtCore`QTimer::timerEvent(QTimerEvent*) [inlined] QTimer::timeout(this=0x00006000039e9a50, _t1=QPrivateSignal @ 0x000070000f3b3aa8) at moc_qtimer.cpp:224:5 [opt]
    frame #15: 0x0000000102e5d345 QtCore`QTimer::timerEvent(this=0x00006000039e9a50, e=<unavailable>) at qtimer.cpp:258:14 [opt]
    frame #16: 0x0000000102e41a99 QtCore`QObject::event(this=0x00006000039e9a50, e=0x000070000f3b3d50) at qobject.cpp:1427:9 [opt]
    frame #17: 0x0000000101a59937 QtWidgets`QApplicationPrivate::notify_helper(this=<unavailable>, receiver=0x00006000039e9a50, e=0x000070000f3b3d50) at qapplication.cpp:3287:26 [opt]
    frame #18: 0x0000000101a5a742 QtWidgets`QApplication::notify(this=0x00007ff7bfeff040, receiver=<unavailable>, e=<unavailable>) at qapplication.cpp:0 [opt]
    frame #19: 0x0000000102df9b94 QtCore`QCoreApplication::notifyInternal2(receiver=0x00006000039e9a50, event=0x000070000f3b3d50) at qcoreapplication.cpp:1134:18 [opt]
    frame #20: 0x0000000102f8cd56 QtCore`QTimerInfoList::activateTimers(this=<unavailable>) at qtimerinfo_unix.cpp:434:13 [opt]
    frame #21: 0x0000000102f90354 QtCore`QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) [inlined] QEventDispatcherUNIXPrivate::activateTimers(this=<unavailable>) at qeventdispatcher_unix.cpp:196:22 [opt]
    frame #22: 0x0000000102f90345 QtCore`QEventDispatcherUNIX::processEvents(this=<unavailable>, flags=(i = 36)) at qeventdispatcher_unix.cpp:472:23 [opt]
    frame #23: 0x0000000102e035b6 QtCore`QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) [inlined] QEventLoop::processEvents(this=0x000070000f3b3eb0, flags=(i = 36)) at qeventloop.cpp:100:55 [opt]
    frame #24: 0x0000000102e03598 QtCore`QEventLoop::exec(this=0x000070000f3b3eb0, flags=<unavailable>) at qeventloop.cpp:182:9 [opt]
    frame #25: 0x0000000102eed01a QtCore`QThread::exec(this=<unavailable>) at qthread.cpp:578:32 [opt]
    frame #26: 0x0000000100019bfc clxboosted`EmailSchedulerThread::run(this=0x00007ff7bfefee60) at emailscheduler.h:39:9
    frame #27: 0x0000000102f8de19 QtCore`QThreadPrivate::start(void*) [inlined] QThreadPrivate::start(void*)::$_0::operator()(this=<unavailable>) const at qthread_unix.cpp:326:14 [opt]
    frame #28: 0x0000000102f8dd12 QtCore`QThreadPrivate::start(void*) [inlined] void (anonymous namespace)::terminate_on_exception<QThreadPrivate::start(void*)::$_0>(t=<unavailable>) at qthread_unix.cpp:262:9 [opt]
    frame #29: 0x0000000102f8dd12 QtCore`QThreadPrivate::start(arg=0x00007ff7bfefee60) at qthread_unix.cpp:285:5 [opt]
    frame #30: 0x00007ff81240a18b libsystem_pthread.dylib`_pthread_start + 99
    frame #31: 0x00007ff812405ae3 libsystem_pthread.dylib`thread_start + 15

**Comment by dantti** [comment]
please test current master, there's a potential fix

**Comment by dantti** [comment]
closing as this was probably fixed
